version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "8000:8000"
    command: uvicorn Application.Backend.app:app --host 0.0.0.0 --port 8000
    volumes:
      - ./Application/Backend:/app/Application/Backend    

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "80:3000"
    command: npm start -- --host 0.0.0.0
